import { useEffect, useMemo, useState } from 'react';
import { locale, t } from '@meetcc/shared/i18n';
import type { Analysis, AnalysisRecord, Meeting, MiniContext } from '@meetcc/shared';
import {
  appendAudit,
  saveContext,
  getContext,
  getMeetingTags,
  saveMeetingTags,
  getMiniContexts,
  watchStorage,
  MINI_CONTEXTS_KEY,
  CONTEXT_PREFIX,
  MEETING_TAGS_PREFIX,
} from '@meetcc/shared';
import { db } from '../lib/db';
import { toMarkdown } from '@meetcc/exporters/markdown';
import { obsidianPath, toObsidian } from '@meetcc/exporters/obsidian';
import { GATE_EVENT } from '@meetcc/exporters/gate';
import { datedCount, toChecklist, toIcs } from '@meetcc/exporters/tasks';
import { lazyImport } from '../lib/lazy';
import { classifyBridgeError } from '../lib/bridgeError';
import { Button, TextArea, useToast } from '@meetcc/ui';

function downloadBlob(name: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="sum-section">
      <h3>{title}</h3>
      {children}
    </section>
  );
}

const List = ({ items }: { items: string[] }) =>
  items.length ? (
    <ul>
      {items.map((x, i) => (
        <li key={i}>{x}</li>
      ))}
    </ul>
  ) : (
    <p className="dim">—</p>
  );

function ActionItemsToolbar({ meeting, analysis }: { meeting: Meeting; analysis: Analysis }) {
  const toast = useToast();
  const dated = datedCount(analysis);
  return (
    <div className="task-export">
      <Button variant="ghost"
        onClick={async () => {
          await navigator.clipboard.writeText(toChecklist(analysis));
          toast('success', t('ext.summary.checklistCopied'));
        }}
      >
        ⧉ Copy checklist
      </Button>
      <Button variant="ghost"
        disabled={!dated}
        title={dated ? '' : t('ext.summary.noDatedActions')}
        onClick={() => {
          downloadBlob(`${meeting.id}-tasks.ics`, new Blob([toIcs(meeting, analysis)], { type: 'text/calendar' }));
          toast('success', t('ext.summary.icsDownloaded', { count: dated }));
        }}
      >
        ⬇ .ics{dated ? ` (${dated})` : ''}
      </Button>
    </div>
  );
}

function Result({ meeting, analysis }: { meeting: Meeting; analysis: Analysis }) {
  return (
    <div className="summary-body">
      <Section title="Executive Summary">
        <p>{analysis.executiveSummary}</p>
      </Section>
      <Section title={t('ext.summary.section.timeline')}>
        {analysis.timeline.length ? (
          <ol className="timeline">
            {analysis.timeline.map((t, i) => (
              <li key={i}>
                <span className="tl-time">{t.time || '—'}</span>
                <span>{t.topic}</span>
              </li>
            ))}
          </ol>
        ) : (
          <p className="dim">—</p>
        )}
      </Section>
      <Section title="Key Discussion">
        <List items={analysis.keyDiscussions} />
      </Section>
      <Section title="Decisions">
        {analysis.decisions.length ? (
          <ul className="decisions">
            {analysis.decisions.map((d, i) => (
              <li key={i}>
                <div className="decision-what">
                  {d.what}
                  {d.topic && <span className="topic-tag">{d.topic}</span>}
                </div>
                {d.why && <div className="decision-why">Alasan: {d.why}</div>}
                {d.rejected.length > 0 && (
                  <div className="decision-rejected">Ditolak: {d.rejected.join('; ')}</div>
                )}
              </li>
            ))}
          </ul>
        ) : (
          <p className="dim">—</p>
        )}
      </Section>
      <Section title="Action Items">
        {analysis.actionItems.length ? (
          <>
          <ActionItemsToolbar meeting={meeting} analysis={analysis} />
          <table className="ai-table">
            <thead>
              <tr>
                <th>Task</th>
                <th>Owner</th>
                <th>Due</th>
              </tr>
            </thead>
            <tbody>
              {analysis.actionItems.map((a, i) => (
                <tr key={i}>
                  <td>{a.task}</td>
                  <td>{a.owner || '—'}</td>
                  <td>{a.due || '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
          </>
        ) : (
          <p className="dim">—</p>
        )}
      </Section>
      <Section title="Risks">
        <List items={analysis.risks} />
      </Section>
      <Section title="Open Questions">
        <List items={analysis.openQuestions} />
      </Section>
      <Section title="Next Steps">
        <List items={analysis.nextSteps} />
      </Section>
      <p className="dim generated-note">
        Generated by AI — verifikasi keputusan penting terhadap transcript {meeting.id}.
      </p>
    </div>
  );
}

function appendContextTagsToMap(map: Map<string, MiniContext[]>, c: MiniContext): void {
  for (let j = 0; j < c.tags.length; j++) {
    const tg = c.tags[j].toLowerCase();
    let list = map.get(tg);
    if (!list) {
      list = [];
      map.set(tg, list);
    }
    list.push(c);
  }
}

function buildTagToContextsMap(contexts: MiniContext[]): Map<string, MiniContext[]> {
  const map = new Map<string, MiniContext[]>();
  for (let i = 0; i < contexts.length; i++) {
    appendContextTagsToMap(map, contexts[i]);
  }
  return map;
}

function ContextCard({ meeting }: { meeting: Meeting }) {
  const [context, setContext] = useState(meeting.context ?? '');
  const [selectedTags, setSelectedTags] = useState<string[]>(meeting.tags ?? []);
  const [open, setOpen] = useState(!meeting.context?.trim() && (!meeting.tags || meeting.tags.length === 0));
  const [saved, setSaved] = useState(false);
  const [availableContexts, setAvailableContexts] = useState<MiniContext[]>([]);
  const [popoverOpen, setPopoverOpen] = useState(false);
  const toast = useToast();

  const loadMiniContextsList = () => {
    void getMiniContexts().then(setAvailableContexts).catch(() => undefined);
  };

  useEffect(() => {
    loadMiniContextsList();
    return watchStorage(loadMiniContextsList, [MINI_CONTEXTS_KEY]);
  }, []);

  useEffect(() => {
    let alive = true;
    void getContext(meeting.id).then((stored) => {
      if (alive) {
        const val = stored || meeting.context || '';
        setContext(val);
      }
    });
    void getMeetingTags(meeting.id).then((storedTags) => {
      if (alive) {
        setSelectedTags(storedTags || meeting.tags || []);
      }
    });
    return () => {
      alive = false;
    };
  }, [meeting.id, meeting.context, meeting.tags]);

  useEffect(() => {
    return watchStorage(() => {
      void getContext(meeting.id).then((ctx) => {
        if (ctx !== undefined) setContext(ctx);
      });
      void getMeetingTags(meeting.id).then((tags) => {
        if (tags !== undefined) setSelectedTags(tags);
      });
    }, [CONTEXT_PREFIX + meeting.id, MEETING_TAGS_PREFIX + meeting.id]);
  }, [meeting.id]);

  const tagToContexts = useMemo(() => buildTagToContextsMap(availableContexts), [availableContexts]);

  const uniqueTags = useMemo(() => {
    return Array.from(tagToContexts.keys()).sort();
  }, [tagToContexts]);

  const tagCounts = useMemo(() => {
    const map = new Map<string, number>();
    for (const [tg, list] of tagToContexts.entries()) {
      map.set(tg, list.length);
    }
    return map;
  }, [tagToContexts]);

  const handleSave = async () => {
    await saveContext(meeting.id, context);
    await db('set-session-agenda', { id: meeting.id, agenda: context }).catch(() => undefined);
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
    toast('success', t('ext.summary.contextSaved'));
  };

  const toggleTag = async (tag: string) => {
    const lower = tag.toLowerCase();
    const isAttached = selectedTags.some((t) => t.toLowerCase() === lower);
    const nextTags = isAttached
      ? selectedTags.filter((t) => t.toLowerCase() !== lower)
      : [...selectedTags, lower];
    setSelectedTags(nextTags);
    await saveMeetingTags(meeting.id, nextTags).catch(() => undefined);
    toast('success', t(isAttached ? 'ext.header.tagDetached' : 'ext.header.tagAttached', { tag }));
  };

  const isCtxActive = (ctx: MiniContext) => {
    const termLower = ctx.term.toLowerCase();
    return selectedTags.some(
      (t) => t.toLowerCase() === termLower || ctx.tags.some((tg) => tg.toLowerCase() === t.toLowerCase())
    );
  };

  const toggleSingle = async (ctx: MiniContext) => {
    const termLower = ctx.term.toLowerCase();
    const isAttached = selectedTags.some((t) => t.toLowerCase() === termLower);
    const nextTags = isAttached
      ? selectedTags.filter((t) => t.toLowerCase() !== termLower)
      : [...selectedTags, termLower];
    setSelectedTags(nextTags);
    await saveMeetingTags(meeting.id, nextTags).catch(() => undefined);
    toast('success', t(isAttached ? 'ext.header.tagDetached' : 'ext.header.tagAttached', { tag: ctx.term }));
  };

  const hasContext = !!context.trim() || selectedTags.length > 0;

  return (
    <div className="summary-context-card">
      <Button type="button"
      className="summary-context-header"
      onClick={() => setOpen((o) => !o)}
      aria-expanded={open}><span className="summary-context-title">
        {t('ext.summary.contextTitle')}
        {hasContext && <span className="context-indicator" />}
      </span>
      <span className="summary-context-preview dim">
        {context.trim()
          ? context.trim().slice(0, 45) + (context.trim().length > 45 ? '…' : '')
          : selectedTags.length > 0
            ? selectedTags.map((tg) => `#${tg}`).join(' ')
            : t('ext.summary.contextHint')}
      </span>
      <span className="summary-context-arrow">{open ? '▲' : '▼'}</span></Button>
      {open && (
        <div className="summary-context-body">
          <TextArea
            className="summary-context-input"
            value={context}
            placeholder={t('ext.summary.contextPlaceholder')}
            onChange={(e) => setContext(e.target.value)}
            onBlur={handleSave}
            rows={3}
          />
          {selectedTags.length > 0 && (
            <div className="summary-active-tags-row">
              <span className="summary-active-tags-label">{t('ext.header.activeTags')}:</span>
              <div className="summary-active-tags-list">
                {selectedTags.map((tg) => (
                  <span key={tg} className="summary-active-tag-chip">
                    #{tg}
                    <Button
                      type="button"
                      className="summary-active-tag-remove"
                      onClick={() => void toggleTag(tg)}
                      aria-label={t('ext.header.close')}
                    >
                      ✕
                    </Button>
                  </span>
                ))}
              </div>
            </div>
          )}
          <div className="summary-context-quick-insert">
            <span className="quick-insert-label">
              ✦ {t('ext.header.insertContext')}:
            </span>
            <div className="quick-insert-tags" title={t('ext.header.insertByTag')}>
              {uniqueTags.map((tg) => {
                const count = tagCounts.get(tg) ?? 0;
                const isAttached = selectedTags.some((t) => t.toLowerCase() === tg.toLowerCase());
                return (
                  <Button key={tg}
                  type="button"
                  className={`quick-insert-tag-btn ${isAttached ? 'active' : ''}`}
                  onClick={() => void toggleTag(tg)}
                  title={t('ext.header.insertAllWithTag', { tag: tg, count })}>
                    {isAttached ? '✓' : '+'} #{tg} <span className="tag-count">({count})</span></Button>
                );
              })}
              {availableContexts.length > 0 && (
                <div className="quick-insert-single-wrap">
                  <Button type="button"
                  className="quick-insert-single-btn"
                  onClick={() => setPopoverOpen((v) => !v)}>
                    ✦ {t('ext.header.insertSingle')} ▾
                  </Button>
                  {popoverOpen && (
                    <div className="summary-context-popover">
                      <div className="summary-popover-head">
                        <span className="summary-popover-title">{t('ext.header.contextPopoverTitle')}</span>
                        <Button type="button"
                        className="summary-popover-close"
                        onClick={() => setPopoverOpen(false)}
                        aria-label={t('ext.header.close')}>
                          ✕
                        </Button>
                      </div>
                      <div className="summary-popover-item-list">
                        {availableContexts.map((ctx) => {
                          const active = isCtxActive(ctx);
                          return (
                            <Button key={ctx.id}
                            type="button"
                            className={`summary-ctx-item-btn ${active ? 'active' : ''}`}
                            onClick={() => void toggleSingle(ctx)}>
                              <span className="ctx-item-term">{active ? '✓ ' : ''}{ctx.term}</span>
                              <span className="dim ctx-item-def">{ctx.definition}</span>
                            </Button>
                          );
                        })}
                      </div>
                    </div>
                  )}
                </div>
              )}
              {availableContexts.length === 0 && (
                <span className="dim" style={{ fontSize: 11 }}>
                  {t('ext.header.noContextsAvailable')}
                </span>
              )}
            </div>
          </div>
          <div className="summary-context-footer">
            <span className="dim" style={{ fontSize: 11 }}>
              {t('ext.summary.contextHint')}
            </span>
            <Button type="button" className="small" variant="primary" onClick={handleSave}>
              {saved ? t('ext.summary.contextSaved') : t('ext.summary.contextSave')}
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}

interface Props {
  meeting: Meeting;
  record: AnalysisRecord | null;
  live: boolean;
}

export function SummaryView({ meeting, record, live }: Props) {
  const toast = useToast();
  const [busy, setBusy] = useState(false);

  const regenerate = async () => {
    setBusy(true);
    try {
      const res = await chrome.runtime.sendMessage({
        type: 'regenerate',
        meetingId: meeting.id,
      });
      if (res?.ok) toast('success', live ? t('ext.summary.momDone') : t('ext.summary.notesDone'));
      else toast('error', t('ext.failed', { error: res?.error ?? res?.reason ?? t('ext.unknownError') }));
    } catch (e) {
      toast('error', t('ext.failed', { error: (e as Error).message }));
    } finally {
      setBusy(false);
    }
  };

  const actions = (analysis: Analysis) => (
    <div className="subbar">
      <Button onClick={() => {
        downloadBlob(
          `${meeting.id}.md`,
          new Blob([toMarkdown(meeting, analysis)], { type: 'text/markdown' }),
        );
        toast('success', t('ext.summary.markdownDownloaded'));
      }}>
        ⬇ Markdown
      </Button>
      <Button onClick={() => {
        // §32.1 probe: Obsidian-friendly export + local audit event for the
        // G1/G2 gate metrics. No telemetry — the event stays in the device ring.
        downloadBlob(
          obsidianPath(meeting).split('/').pop()!,
          new Blob([toObsidian(meeting, analysis)], { type: 'text/markdown' }),
        );
        void appendAudit(GATE_EVENT, 'meetings=1').catch(() => undefined);
        toast('success', t('ext.summary.obsidianDownloaded'));
      }}>
        ⬇ Obsidian
      </Button>
      <Button
        disabled={busy}
        onClick={async () => {
          setBusy(true);
          try {
            // jsPDF + mermaid are heavy; load them only when actually exporting
            const [{ toPdf }, { renderPng }, { orgLogoPng }] = await Promise.all([
              lazyImport(() => import('@meetcc/exporters/pdf')),
              lazyImport(() => import('../lib/mermaid')),
              lazyImport(() => import('../lib/logo')),
            ]);
            // rasterize diagrams in the browser; a bad one is skipped, not fatal
            const rendered = await Promise.all(
              (analysis.diagrams ?? []).map(async (d) => {
                try {
                  const png = await renderPng(d.mermaid);
                  return { title: d.title, ...png };
                } catch {
                  return null;
                }
              }),
            );
            const diagrams = rendered.filter((d): d is NonNullable<typeof d> => d !== null);
            const logo = await orgLogoPng();
            downloadBlob(`${meeting.id}.pdf`, toPdf(meeting, analysis, diagrams, logo));
            toast('success', t('ext.docs.pdfDownloaded'));
          } catch (e) {
            toast('error', t('ext.docs.pdfFailed', { error: (e as Error).message }));
          } finally {
            setBusy(false);
          }
        }}
      >
        ⬇ PDF
      </Button>
      <Button disabled={busy}
      onClick={async () => {
        setBusy(true);
        try {
          const res = (await chrome.runtime.sendMessage({
            type: 'bridge-deliver-meeting',
            meetingId: meeting.id,
          })) as { ok?: boolean; error?: string };
          if (res?.ok) {
            toast('success', t('ext.summary.desktopSent'));
          } else {
            const err = res?.error ?? '';
            const classified = classifyBridgeError(err);
            if (classified === 'not_found' || classified === 'not_registered') {
              toast('error', t('ext.summary.desktopNotConnected'));
            } else {
              toast('error', t('ext.summary.desktopFailed', { error: err }));
            }
          }
        } catch (e) {
          toast('error', t('ext.summary.desktopFailed', { error: (e as Error).message }));
        } finally {
          setBusy(false);
        }
      }}>{t('ext.summary.exportDesktop')}</Button>
      <span className="spacer" />
      <Button onClick={regenerate} disabled={busy}>{busy ? 'Memproses…' : live ? '↻ Perbarui MoM' : '↻ Regenerate'}</Button>
    </div>
  );

  if (record?.status === 'done') {
    return (
      <>
        {actions(record.analysis)}
        <div className="summary-meta dim">
          Provider: {record.provider} · {new Date(record.generatedAt).toLocaleString(locale())}
          {record.provisional &&
            ' · MoM sementara dari transcript sejauh ini — diganti otomatis setelah meeting selesai'}
        </div>
        <ContextCard meeting={meeting} />
        <Result meeting={meeting} analysis={record.analysis} />
      </>
    );
  }

  if (record?.status === 'processing') {
    const steps = ['Transcript', 'AI Processing', t('ext.summary.step.saving')];
    const active = record.step === 'ai' ? 1 : 2;
    // taking too long usually means a crashed/hung run — offer a manual restart
    const slow = Date.now() - Date.parse(record.startedAt) > 45_000;
    return (
      <div className="summary-body">
        <div className="progress" role="progressbar" aria-label="AI processing">
          {steps.map((s, i) => (
            <div key={s} className={`step ${i < active ? 'done' : i === active ? 'active' : ''}`}>
              <span className="step-dot" />
              {s}
            </div>
          ))}
        </div>
        {slow && (
          <div className="subbar" style={{ border: 0, padding: '4px 0' }}>
            <span className="dim" style={{ fontSize: 11 }}>
              Lama? Proses mungkin terhenti.
            </span>
            <Button onClick={regenerate} disabled={busy}>{busy ? t('ext.summary.processing') : t('ext.summary.restart')}</Button>
          </div>
        )}
        {[0, 1, 2, 3].map((i) => (
          <div key={i} className="skeleton skeleton-block" />
        ))}
      </div>
    );
  }

  if (record?.status === 'error') {
    return (
      <div className="empty-state">
        <div className="error-box" role="alert">
          <strong>{t('ext.summary.analysisFailed')}</strong>
          <p>{record.error}</p>
        </div>
        <Button variant="primary" onClick={regenerate} disabled={busy}>
          {busy ? t('ext.summary.processing') : t('ext.summary.retry')}
        </Button>
      </div>
    );
  }

  return (
    <div className="empty-state">
      <div className="empty-glyph">AI</div>
      <p>{live ? t('ext.summary.liveTitle') : t('ext.summary.emptyTitle')}</p>
      <p className="empty-hint">
        {live
          ? t('ext.summary.liveHint')
          : t('ext.summary.emptyHint')}
      </p>
      <ContextCard meeting={meeting} />
      <Button variant="primary" onClick={regenerate} disabled={busy}>
        {busy
          ? t('ext.summary.processing')
          : live
            ? t('ext.summary.makeMom')
            : t('ext.summary.generate')}
      </Button>
    </div>
  );
}
