import { useState } from 'react';
import type { Analysis, AnalysisRecord, Meeting } from '@meetcc/shared';
import { toMarkdown } from '@meetcc/exporters/markdown';
import { datedCount, toChecklist, toIcs } from '@meetcc/exporters/tasks';
import { useToast } from '../toast';

function downloadBlob(name: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="sum-section">
      <h3>{title}</h3>
      {children}
    </section>
  );
}

const List = ({ items }: { items: string[] }) =>
  items.length ? (
    <ul>
      {items.map((x, i) => (
        <li key={i}>{x}</li>
      ))}
    </ul>
  ) : (
    <p className="dim">—</p>
  );

function ActionItemsToolbar({ meeting, analysis }: { meeting: Meeting; analysis: Analysis }) {
  const toast = useToast();
  const dated = datedCount(analysis);
  return (
    <div className="task-export">
      <button
        className="ghost"
        onClick={async () => {
          await navigator.clipboard.writeText(toChecklist(analysis));
          toast('success', 'Checklist disalin.');
        }}
      >
        ⧉ Copy checklist
      </button>
      <button
        className="ghost"
        disabled={!dated}
        title={dated ? '' : 'Tidak ada action item dengan tanggal terstruktur (yyyy-mm-dd)'}
        onClick={() => {
          downloadBlob(`${meeting.id}-tasks.ics`, new Blob([toIcs(meeting, analysis)], { type: 'text/calendar' }));
          toast('success', `${dated} event kalender diunduh.`);
        }}
      >
        ⬇ .ics{dated ? ` (${dated})` : ''}
      </button>
    </div>
  );
}

function Result({ meeting, analysis }: { meeting: Meeting; analysis: Analysis }) {
  return (
    <div className="summary-body">
      <Section title="Executive Summary">
        <p>{analysis.executiveSummary}</p>
      </Section>
      <Section title="Timeline Pembahasan">
        {analysis.timeline.length ? (
          <ol className="timeline">
            {analysis.timeline.map((t, i) => (
              <li key={i}>
                <span className="tl-time">{t.time || '—'}</span>
                <span>{t.topic}</span>
              </li>
            ))}
          </ol>
        ) : (
          <p className="dim">—</p>
        )}
      </Section>
      <Section title="Key Discussion">
        <List items={analysis.keyDiscussions} />
      </Section>
      <Section title="Decisions">
        {analysis.decisions.length ? (
          <ul className="decisions">
            {analysis.decisions.map((d, i) => (
              <li key={i}>
                <div className="decision-what">
                  {d.what}
                  {d.topic && <span className="topic-tag">{d.topic}</span>}
                </div>
                {d.why && <div className="decision-why">Alasan: {d.why}</div>}
                {d.rejected.length > 0 && (
                  <div className="decision-rejected">Ditolak: {d.rejected.join('; ')}</div>
                )}
              </li>
            ))}
          </ul>
        ) : (
          <p className="dim">—</p>
        )}
      </Section>
      <Section title="Action Items">
        {analysis.actionItems.length ? (
          <>
          <ActionItemsToolbar meeting={meeting} analysis={analysis} />
          <table className="ai-table">
            <thead>
              <tr>
                <th>Task</th>
                <th>Owner</th>
                <th>Due</th>
              </tr>
            </thead>
            <tbody>
              {analysis.actionItems.map((a, i) => (
                <tr key={i}>
                  <td>{a.task}</td>
                  <td>{a.owner || '—'}</td>
                  <td>{a.due || '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
          </>
        ) : (
          <p className="dim">—</p>
        )}
      </Section>
      <Section title="Risks">
        <List items={analysis.risks} />
      </Section>
      <Section title="Open Questions">
        <List items={analysis.openQuestions} />
      </Section>
      <Section title="Next Steps">
        <List items={analysis.nextSteps} />
      </Section>
      <p className="dim generated-note">
        Generated by AI — verifikasi keputusan penting terhadap transcript {meeting.id}.
      </p>
    </div>
  );
}

interface Props {
  meeting: Meeting;
  record: AnalysisRecord | null;
  live: boolean;
}

export function SummaryView({ meeting, record, live }: Props) {
  const toast = useToast();
  const [busy, setBusy] = useState(false);

  const regenerate = async () => {
    setBusy(true);
    try {
      const res = await chrome.runtime.sendMessage({
        type: 'regenerate',
        meetingId: meeting.id,
      });
      if (res?.ok) toast('success', 'Notulen selesai dibuat.');
      else toast('error', `Gagal: ${res?.error ?? res?.reason ?? 'unknown'}`);
    } catch (e) {
      toast('error', `Gagal: ${(e as Error).message}`);
    } finally {
      setBusy(false);
    }
  };

  const actions = (analysis: Analysis) => (
    <div className="subbar">
      <button
        onClick={() => {
          downloadBlob(
            `${meeting.id}.md`,
            new Blob([toMarkdown(meeting, analysis)], { type: 'text/markdown' }),
          );
          toast('success', 'Markdown diunduh.');
        }}
      >
        ⬇ Markdown
      </button>
      <button
        disabled={busy}
        onClick={async () => {
          setBusy(true);
          try {
            // jsPDF + mermaid are heavy; load them only when actually exporting
            const [{ toPdf }, { renderPng }, { orgLogoPng }] = await Promise.all([
              import('@meetcc/exporters/pdf'),
              import('../lib/mermaid'),
              import('../lib/logo'),
            ]);
            // rasterize diagrams in the browser; a bad one is skipped, not fatal
            const rendered = await Promise.all(
              (analysis.diagrams ?? []).map(async (d) => {
                try {
                  const png = await renderPng(d.mermaid);
                  return { title: d.title, ...png };
                } catch {
                  return null;
                }
              }),
            );
            const diagrams = rendered.filter((d): d is NonNullable<typeof d> => d !== null);
            const logo = await orgLogoPng();
            downloadBlob(`${meeting.id}.pdf`, toPdf(meeting, analysis, diagrams, logo));
            toast('success', 'PDF diunduh.');
          } catch (e) {
            toast('error', `Gagal membuat PDF: ${(e as Error).message}`);
          } finally {
            setBusy(false);
          }
        }}
      >
        ⬇ PDF
      </button>
      <span className="spacer" />
      <button onClick={regenerate} disabled={busy || live}>
        {busy ? 'Memproses…' : '↻ Regenerate'}
      </button>
    </div>
  );

  if (record?.status === 'done') {
    return (
      <>
        {actions(record.analysis)}
        <div className="summary-meta dim">
          Provider: {record.provider} · {new Date(record.generatedAt).toLocaleString('id-ID')}
        </div>
        <Result meeting={meeting} analysis={record.analysis} />
      </>
    );
  }

  if (record?.status === 'processing') {
    const steps = ['Transcript', 'AI Processing', 'Menyimpan'];
    const active = record.step === 'ai' ? 1 : 2;
    return (
      <div className="summary-body">
        <div className="progress" role="progressbar" aria-label="AI processing">
          {steps.map((s, i) => (
            <div key={s} className={`step ${i < active ? 'done' : i === active ? 'active' : ''}`}>
              <span className="step-dot" />
              {s}
            </div>
          ))}
        </div>
        {[0, 1, 2, 3].map((i) => (
          <div key={i} className="skeleton skeleton-block" />
        ))}
      </div>
    );
  }

  if (record?.status === 'error') {
    return (
      <div className="empty-state">
        <div className="error-box" role="alert">
          <strong>Analisis gagal</strong>
          <p>{record.error}</p>
        </div>
        <button className="primary" onClick={regenerate} disabled={busy}>
          {busy ? 'Memproses…' : 'Coba lagi'}
        </button>
      </div>
    );
  }

  return (
    <div className="empty-state">
      <div className="empty-glyph">AI</div>
      <p>{live ? 'Meeting masih berlangsung.' : 'Belum ada notulen.'}</p>
      <p className="empty-hint">
        {live
          ? 'Notulen dibuat otomatis begitu meeting selesai.'
          : 'Jalankan analisis AI untuk ringkasan, keputusan, dan action items.'}
      </p>
      {!live && (
        <button className="primary" onClick={regenerate} disabled={busy}>
          {busy ? 'Memproses…' : 'Generate sekarang'}
        </button>
      )}
    </div>
  );
}
