import {
  participants,
  startedAt,
  type Analysis,
  type Decision,
  type Meeting,
} from '@meetcc/shared'
import { locale, t } from '@meetcc/shared/i18n';

const section = (title: string, body: string): string =>
  body.trim() ? `## ${title}\n\n${body.trim()}\n` : ''

const bullets = (items: string[]): string =>
  items.map((i) => `- ${i}`).join('\n')

function decisionsMd(decisions: Decision[]): string {
  return decisions
    .map((d) => {
      const lines = [`- **${d.what}**${d.topic ? ` \`${d.topic}\`` : ''}`]
      if (d.why) lines.push(`  - Alasan: ${d.why}`)
      if (d.rejected.length) lines.push(`  - Ditolak: ${d.rejected.join('; ')}`)
      return lines.join('\n')
    })
    .join('\n')
}

function fmtDate(iso: string | null): string {
  return iso
    ? new Date(iso).toLocaleString(locale(), {
        dateStyle: 'full',
        timeStyle: 'short',
      })
    : '—'
}

export function toMarkdown(meeting: Meeting, analysis: Analysis): string {
  const people = participants(meeting)
  const parts: string[] = [
    `# Meeting Notes — ${meeting.id}`,
    '',
    section(
      'Meeting Information',
      [
        `- **Meeting ID**: ${meeting.id}`,
        `- **Tanggal**: ${fmtDate(startedAt(meeting))}`,
        t('pkg.export.transcriptLines', { count: meeting.entries.length }),
      ].join('\n'),
    ),
    section('Participants', bullets(people)),
    section(
      'Timeline',
      analysis.timeline
        .map((t) => `- **${t.time || '—'}** — ${t.topic}`)
        .join('\n'),
    ),
    section('Executive Summary', analysis.executiveSummary),
    section('Key Discussion', bullets(analysis.keyDiscussions)),
    section('Decisions', decisionsMd(analysis.decisions)),
    section(
      'Action Items',
      analysis.actionItems.length
        ? [
            '| Task | Owner | Due |',
            '| --- | --- | --- |',
            ...analysis.actionItems.map(
              (a) => `| ${a.task} | ${a.owner || '—'} | ${a.due || '—'} |`,
            ),
          ].join('\n')
        : '',
    ),
    section('Risks', bullets(analysis.risks)),
    section('Open Questions', bullets(analysis.openQuestions)),
    section('Next Steps', bullets(analysis.nextSteps)),
    section(
      'Diagram',
      (analysis.diagrams ?? [])
        .map((d) => `### ${d.title}\n\n\`\`\`mermaid\n${d.mermaid}\n\`\`\``)
        .join('\n\n'),
    ),
    '---',
    `_Generated by Meet Companion AI — ${new Date().toISOString()}_`,
    '',
    '_powered by suiflex_',
  ]
  return parts.filter(Boolean).join('\n')
}
