import { jsPDF } from 'jspdf'
import { locale, t } from '@meetcc/shared/i18n';
import {
  participants,
  startedAt,
  type Analysis,
  type Meeting,
} from '@meetcc/shared'

export const M = 18 // page margin, mm
export const W = 210 - M * 2

/** A Mermaid diagram already rasterized to PNG by the browser (see
 *  apps/extension/src/lib/mermaid.ts). exporters stays DOM-free: it only
 *  places the finished bitmap, keeping this package node-testable. */
export interface PdfDiagram {
  title: string
  dataUrl: string
  wPx: number
  hPx: number
}

/** Wide diagrams get their own landscape page so nodes don't shrink to ants. */
function addDiagramPage(pdf: jsPDF, d: PdfDiagram): void {
  const landscape = d.wPx / Math.max(1, d.hPx) > 1.4
  const pageW = landscape ? 297 : 210
  const pageH = landscape ? 210 : 297
  pdf.addPage('a4', landscape ? 'landscape' : 'portrait')

  pdf
    .setFont('helvetica', 'bold')
    .setFontSize(13)
    .setTextColor(...ACCENT)
  pdf.text(d.title, M, M + 4)

  const top = M + 12
  const availW = pageW - M * 2
  const availH = pageH - top - 14 // leave room for footer
  const aspect = d.wPx / Math.max(1, d.hPx)
  let w = availW
  let h = w / aspect
  if (h > availH) {
    h = availH
    w = h * aspect
  }
  pdf.addImage(d.dataUrl, 'PNG', (pageW - w) / 2, top, w, h)
}

export const INK: [number, number, number] = [24, 28, 36]
export const DIM: [number, number, number] = [110, 118, 132]
export const ACCENT: [number, number, number] = [22, 130, 84]

/** Optional organization logo, pre-rasterized in the browser (transparent PNG). */
export interface PdfLogo {
  dataUrl: string
  wPx: number
  hPx: number
}

/** Dark branded cover page shared by every PDF this product emits. */
export function drawCover(
  pdf: jsPDF,
  opts: {
    kicker: string
    title: string
    subtitle: string
    date: string
    logo?: PdfLogo | null
  },
): void {
  pdf.setFillColor(13, 17, 23)
  pdf.rect(0, 0, 210, 297, 'F')
  pdf.setFillColor(...ACCENT)
  pdf.rect(0, 118, 210, 1.2, 'F')
  if (opts.logo) {
    const h = 16
    const w = (opts.logo.wPx / Math.max(1, opts.logo.hPx)) * h
    pdf.addImage(opts.logo.dataUrl, 'PNG', M, 64, w, h)
  }
  pdf
    .setFont('helvetica', 'bold')
    .setFontSize(11)
    .setTextColor(...ACCENT)
  pdf.text(opts.kicker, M, 96)
  pdf.setFontSize(28).setTextColor(240, 244, 250)
  pdf.text(opts.title, M, 110)
  pdf.setFont('helvetica', 'normal').setFontSize(13).setTextColor(180, 188, 200)
  pdf.text(opts.subtitle, M, 130)
  pdf.setFontSize(10.5)
  pdf.text(opts.date, M, 138)
  pdf.setFontSize(9).setTextColor(130, 138, 150)
  pdf.text('Generated by AI', M, 270)
  pdf.text(new Date().toLocaleString(locale()), M, 276)
  pdf.text('powered by suiflex', M, 282)
}

/** Branding footer on every content page; orientation-aware (diagram pages
 *  may be landscape) — reads the real page box instead of assuming portrait. */
export function drawFooters(pdf: jsPDF, label: string): void {
  const pages = pdf.getNumberOfPages()
  for (let i = 2; i <= pages; i++) {
    pdf.setPage(i)
    const pageW = pdf.internal.pageSize.getWidth()
    const pageH = pdf.internal.pageSize.getHeight()
    pdf
      .setFont('helvetica', 'normal')
      .setFontSize(8)
      .setTextColor(...DIM)
    pdf.text(`Meet Companion — powered by suiflex — ${label}`, M, pageH - 8)
    pdf.text(`${i - 1} / ${pages - 1}`, pageW - M, pageH - 8, {
      align: 'right',
    })
  }
}

export class Doc {
  pdf = new jsPDF({ unit: 'mm', format: 'a4' })
  y = M

  ensure(h: number) {
    if (this.y + h > 297 - M - 10) {
      this.pdf.addPage()
      this.y = M
    }
  }

  heading(text: string) {
    this.ensure(16)
    this.y += 6
    this.pdf
      .setFont('helvetica', 'bold')
      .setFontSize(13)
      .setTextColor(...ACCENT)
    this.pdf.text(text, M, this.y)
    this.y += 2
    this.pdf.setDrawColor(...ACCENT).setLineWidth(0.4)
    this.pdf.line(M, this.y, M + 24, this.y)
    this.y += 6
  }

  para(text: string, opts: { bullet?: boolean; dim?: boolean } = {}) {
    if (!text.trim()) return
    this.pdf.setFont('helvetica', 'normal').setFontSize(10.5)
    this.pdf.setTextColor(...(opts.dim ? DIM : INK))
    const indent = opts.bullet ? 5 : 0
    const lines: string[] = this.pdf.splitTextToSize(text, W - indent)
    for (let i = 0; i < lines.length; i++) {
      this.ensure(5.2)
      if (opts.bullet && i === 0) {
        this.pdf.setFillColor(...ACCENT)
        this.pdf.circle(M + 1.2, this.y - 1.2, 0.8, 'F')
      }
      this.pdf.text(lines[i], M + indent, this.y)
      this.y += 5.2
    }
    this.y += 1
  }

  list(items: string[]) {
    for (const item of items) this.para(item, { bullet: true })
    if (!items.length) this.para('—', { dim: true })
  }
}

export function toPdf(
  meeting: Meeting,
  analysis: Analysis,
  diagrams: PdfDiagram[] = [],
  logo: PdfLogo | null = null,
): Blob {
  const d = new Doc()
  const { pdf } = d
  const date = startedAt(meeting)
  const dateStr = date
    ? new Date(date).toLocaleString(locale(), {
        dateStyle: 'full',
        timeStyle: 'short',
      })
    : '—'

  drawCover(pdf, {
    kicker: 'SUIFLEX — MEET Companion',
    title: 'Meeting Notes',
    subtitle: meeting.id,
    date: dateStr,
    logo,
  })

  // ── body ──
  pdf.addPage()

  d.heading('Meeting Information')
  d.para(`Meeting ID: ${meeting.id}`)
  d.para(`Tanggal: ${dateStr}`)
  d.para(`${t('pkg.export.participants')} ${participants(meeting).join(', ') || '—'}`)
  d.para(`Transcript: ${t('pkg.export.lines', { count: meeting.entries.length })}`)

  d.heading('Executive Summary')
  d.para(analysis.executiveSummary)

  if (analysis.timeline.length) {
    d.heading('Timeline')
    d.list(analysis.timeline.map((t) => `${t.time || '—'} — ${t.topic}`))
  }

  d.heading('Key Discussion')
  d.list(analysis.keyDiscussions)

  d.heading('Decisions')
  if (analysis.decisions.length) {
    for (const dec of analysis.decisions) {
      d.para(`${dec.what}${dec.topic ? ` [${dec.topic}]` : ''}`, {
        bullet: true,
      })
      if (dec.why) d.para(`Alasan: ${dec.why}`, { dim: true })
      if (dec.rejected.length)
        d.para(`Ditolak: ${dec.rejected.join('; ')}`, { dim: true })
    }
  } else {
    d.para('—', { dim: true })
  }

  d.heading('Action Items')
  d.list(
    analysis.actionItems.map(
      (a) =>
        `${a.task}${a.owner ? ` — PIC: ${a.owner}` : ''}${a.due ? ` (due ${a.due})` : ''}`,
    ),
  )

  if (analysis.risks.length) {
    d.heading('Risks')
    d.list(analysis.risks)
  }
  if (analysis.openQuestions.length) {
    d.heading('Open Questions')
    d.list(analysis.openQuestions)
  }
  if (analysis.nextSteps.length) {
    d.heading('Next Steps')
    d.list(analysis.nextSteps)
  }

  // ── diagram pages (each portrait or landscape by aspect ratio) ──
  for (const diagram of diagrams) addDiagramPage(pdf, diagram)

  drawFooters(pdf, meeting.id)

  return pdf.output('blob')
}
