// Registers the Companion native-messaging host for a browser profile.
//
// This is what makes "Kirim rapat selesai ke Companion Desktop" actually
// arrive. Until now the only thing that wrote the host manifest was
// apps/desktop/scripts/install-native-host.sh — a manual dev step that needs
// the repo and npm — so on a normal install the extension called
// sendNativeMessage into a host the browser had never heard of, and the
// failure was swallowed.
//
// Two details decide whether this works at all:
//
//  1. `companion install` runs browsers with --user-data-dir, and Chromium
//     resolves native-messaging manifests relative to the *effective*
//     user-data-dir, not the browser's default profile
//     (docs/spike-native-messaging-installer.md §"per-user manifests").
//     So the manifest belongs inside the dedicated profile — which is also
//     what finally covers Brave / Arc / Chromium / Edge instead of Chrome only.
//
//  2. The host is a Node script. A browser started from Finder or a desktop
//     launcher does not inherit a shell PATH, so `#!/usr/bin/env node` finds
//     nothing and the host dies before it speaks. What gets registered is a
//     wrapper that execs an absolute node.
//
// Firefox is the exception to (1): its manifests are global, not per-profile.

import { createHash } from 'node:crypto';
import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { homedir, platform } from 'node:os';
import { join } from 'node:path';

export const HOST_NAME = 'dev.suiflex.companion';
const DESCRIPTION = 'Companion vault capture host';

/**
 * The id Chromium gives an unpacked extension: first 16 bytes of the SHA-256
 * of the DER public key, each nibble mapped onto a–p. The manifest pins `key`,
 * so this is stable across machines and matches the id in INSTALL.md.
 */
export function extensionIdFromKey(base64Key) {
  const digest = createHash('sha256').update(Buffer.from(base64Key, 'base64')).digest();
  let id = '';
  for (const byte of digest.subarray(0, 16)) {
    id += String.fromCharCode(97 + (byte >> 4)) + String.fromCharCode(97 + (byte & 15));
  }
  return id;
}

/** The extension id the given engine will load `manifest` under. */
export function extensionIdFor(manifest, engine) {
  if (engine === 'gecko') return manifest.browser_specific_settings?.gecko?.id ?? null;
  return manifest.key ? extensionIdFromKey(manifest.key) : null;
}

/**
 * Where the host manifest has to land.
 *
 * Returns `null` on Windows: registration there is a registry write, which
 * install-native-host.ps1 already owns.
 */
export function hostManifestDir(engine, profileDir, plat = platform(), home = homedir()) {
  if (plat === 'win32') return null;
  // Chromium reads it out of whatever user-data-dir it was started with.
  if (engine !== 'gecko') return join(profileDir, 'NativeMessagingHosts');
  // Firefox ignores the profile for this and only looks at the global path.
  return plat === 'darwin'
    ? join(home, 'Library', 'Application Support', 'Mozilla', 'NativeMessagingHosts')
    : join(home, '.mozilla', 'native-messaging-hosts');
}

/** Where the host itself is installed. Never inside a browser profile. */
export function hostInstallDir(plat = platform(), home = homedir()) {
  if (plat === 'darwin') return join(home, 'Library', 'Application Support', 'Companion');
  if (plat === 'win32') return join(process.env.LOCALAPPDATA || join(home, 'AppData', 'Local'), 'Companion');
  return join(home, '.local', 'share', 'companion');
}

/** The manifest body. Chromium allowlists an origin, Gecko an extension id. */
export function hostManifest(extensionId, hostPath, engine) {
  return {
    name: HOST_NAME,
    description: DESCRIPTION,
    path: hostPath,
    type: 'stdio',
    ...(engine === 'gecko'
      ? { allowed_extensions: [extensionId] }
      : { allowed_origins: [`chrome-extension://${extensionId}/`] }),
  };
}

/**
 * The launcher the manifest points at: an absolute node, resolved now, so the
 * host runs no matter how the browser was started.
 */
export function wrapperScript(nodePath, hostPath) {
  return `#!/bin/sh\n# generated by \`companion install\` — do not edit\nexec ${JSON.stringify(nodePath)} ${JSON.stringify(hostPath)} "$@"\n`;
}

/**
 * Install the host and register it for one browser profile.
 *
 * Returns what it wrote so the caller can print it, or `null` when the
 * platform has no file-based registration (Windows).
 */
export function installHost({ browser, profileDir, hostSource, extensionId, nodePath = process.execPath }) {
  const dir = hostManifestDir(browser.engine, profileDir);
  if (!dir) return null;

  const installDir = hostInstallDir();
  mkdirSync(installDir, { recursive: true });
  const hostPath = join(installDir, 'native-host.mjs');
  copyFileSync(hostSource, hostPath);

  const wrapperPath = join(installDir, 'native-host');
  writeFileSync(wrapperPath, wrapperScript(nodePath, hostPath), { mode: 0o755 });

  mkdirSync(dir, { recursive: true });
  const manifestPath = join(dir, `${HOST_NAME}.json`);
  writeFileSync(manifestPath, `${JSON.stringify(hostManifest(extensionId, wrapperPath, browser.engine), null, 2)}\n`);

  return { manifestPath, wrapperPath, hostPath };
}
